before:
  hooks:
    - go mod tidy
    - go generate ./...
builds:
  - id: devcycle_sdk_proxy     # controls the local directory names only
    binary: devcycle-sdk-proxy # controls the actual executable name
    main: ./cmd
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin

dockers:
  - image_templates:
    - "ghcr.io/devcyclehq/sdk-proxy:{{ .Version }}"
    - "ghcr.io/devcyclehq/sdk-proxy:{{ .Tag }}"
    - "ghcr.io/devcyclehq/sdk-proxy:v{{ .Major }}.{{ .Minor }}.{{ .Patch }}"
    - "ghcr.io/devcyclehq/sdk-proxy:latest"
    goos: linux
    goarch: amd64
    dockerfile: Dockerfile
    skip_push: false

archives:
  - format: tar.gz
    # The following template controls the format of the .tar.gz filenames
    name_template: >-
      devcycle_sdk_proxy_
      {{- .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    # use zip for windows archives
    format_overrides:
    - goos: windows
      format: zip
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

nfpms:
  - id: devcycle-sdk-proxy
    package_name: devcycle-sdk-proxy # controls the naming of the packages
    file_name_template: "{{ .ConventionalFileName }}"
    vendor: DevCycle
    homepage: https://devcycle.com/
    maintainer: DevCycle <support@devcycle.com>
    description: |-
      DevCycle SDK Proxy. Used to emulate the DevCycle cloud bucketing API, config CDN, and Events API locally to enable 
      local bucketing in languages that do not support WebAssembly.
    license: MIT
    contents:
      - src: config.json.example
        dst: /etc/devcycle-sdk-proxy/config.json.example
        type: config
    formats:
      - apk
      - deb
      - rpm
    provides:
      - devcycle-sdk-proxy
    suggests:
      - nginx
    version_metadata: git