name: GoReleaser Artifacts

on:
  workflow_run:
    workflows:
      - Release
    types:
      - completed

permissions:
  contents: write
  packages: write
  issues: write

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
        with:
          fetch-depth: 0
      - run: |
          git fetch --force --tags
          latestTag=$(git describe --tags `git rev-list --tags --max-count=1`)
          git checkout $latestTag
      - uses: actions/setup-go@v7
        with:
          go-version: stable
      - uses: goreleaser/goreleaser-action@f06c13b6b1a9625abc9e6e439d9c05a8f2190e94 # v7.2.3
        with:
          distribution: goreleaser
          version: 'v2.6.0'
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.AUTOMATION_USER_TOKEN }}
