name: Release

on:
  workflow_dispatch:
    inputs:
      prerelease:
        description: "Prerelease"
        required: true
        default: false
        type: boolean
      draft:
        description: "Draft"
        required: true
        default: false
        type: boolean
      version-increment-type:
        description: "Which part of the version to increment:"
        required: true
        type: choice
        options:
          - major
          - minor
          - patch
        default: "patch"

permissions:
  contents: write
  packages: write

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      # Check out the repo with credentials that can bypass branch protection, and fetch git history instead of just latest commit
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.AUTOMATION_USER_TOKEN }}
          fetch-depth: 0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to the Container registry
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ${{ env.REGISTRY }}
          username: devcycle-automation
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4.4.0
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - uses: DevCycleHQ/release-action/prepare-release@v2.3.0
        id: prepare-release
        with:
          github-token: ${{ secrets.AUTOMATION_USER_TOKEN }}
          prerelease: ${{ github.event.inputs.prerelease }}
          draft: ${{ github.event.inputs.draft }}
          version-increment-type: ${{ github.event.inputs.version-increment-type }}

      - uses: actions/setup-go@v5
        with:
          go-version: "stable"

      - name: Update and commit version.go file
        run: |
          sed -i 's/const Version = ".*"/const Version = "${{ steps.prepare-release.outputs.next-release-tag }}"/' version.go
          git config --global user.email "foundation-admin@devcycle.com"
          git config --global user.name "DevCycle Automation"
          git add version.go
          git commit -m "Release ${{ steps.prepare-release.outputs.next-release-tag }}"
          git tag ${{ steps.prepare-release.outputs.next-release-tag }}
          git push origin HEAD:main

      - name: Build and push Docker image
        uses: docker/build-push-action@v6.7.0
        with:
          context: .
          push: true
          tags: ghcr.io/devcyclehq/sdk-proxy:${{ steps.prepare-release.outputs.next-release-tag }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - uses: DevCycleHQ/release-action/create-release@v2.3.0
        id: create-release
        with:
          github-token: ${{ secrets.AUTOMATION_USER_TOKEN }}
          tag: ${{ steps.prepare-release.outputs.next-release-tag }}
          target: main
          prerelease: ${{ github.event.inputs.prerelease }}
          draft: ${{ github.event.inputs.draft }}
          changelog: ${{ steps.prepare-release.outputs.changelog }}
      - name: Display link to release
        run: |
          echo "::notice title=Release ID::${{ steps.create-release.outputs.release-id }}"
          echo "::notice title=Release URL::${{ steps.create-release.outputs.release-url }}"
